lsi: false
safe: true
source: /docs
title: Docs | Chris Dixon On Code
descripton: Tech Focused Documentation Articles
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0 # https://github.com/pages-themes/hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one